$script = <<EOF
REPOUSER=pfichtner

apk update 
apk add git
pip install cherrypy

cd /opt/ && git clone https://github.com/$REPOUSER/KataTrainReservation.git
EOF

$run = <<EOF
cd /opt/KataTrainReservation/booking_reference_service && python3 booking_reference_service.py &
cd /opt/KataTrainReservation/train_data_service && python3 start_service.py &
EOF

Vagrant.configure("2") do |config|
  config.vm.box = "maier/alpine-3.4-x86_64"

  config.vm.provider "virtualbox" do |vb|
      vb.customize [ "modifyvm", :id, "--memory", "512"]
      vb.customize [ "modifyvm", :id, "--cpus", "1"]
  end

  config.vm.network "forwarded_port", host: 8081, guest: 8081, auto_correct: true
  config.vm.network "forwarded_port", host: 8082, guest: 8082, auto_correct: true

  if Vagrant.has_plugin?("vagrant-proxyconf")
    puts "proxyconf..."
    if ENV["http_proxy"]
      puts "http_proxy: " + ENV["http_proxy"]
      config.proxy.http   = ENV["http_proxy"]
    end
    if ENV["https_proxy"]
      puts "https_proxy: " + ENV["https_proxy"]
      config.proxy.https   = ENV["https_proxy"]
    end
    if ENV["no_proxy"]
      puts "no_proxy: "     + ENV["no_proxy"]
      config.proxy.no_proxy = ENV["no_proxy"]
    end
  end

  config.vm.provision "shell", inline: $script
  config.vm.provision "shell", inline: $run, run: "always", privileged: false

  config.vm.provision :serverspec do |spec|
      spec.pattern = 'test/*_spec.rb'
  end
end

