Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/boot2docker"
  config.vm.network "forwarded_port", host: 2200, guest: 8081
  config.vm.network "forwarded_port", host: 2201, guest: 8082

  config.vm.provider "virtualbox" do |vb|
      vb.customize [ "modifyvm", :id, "--memory", "512"]
      vb.customize [ "modifyvm", :id, "--cpus", "1"]
  end

  config.vm.provision "docker" do |d|
    d.run "train_data_service",         image: "pfichtner/docker-katatrainreservation-tds", args: "-p 8081:8081"
    d.run "booking_reference_service",  image: "pfichtner/docker-katatrainreservation-brs", args: "-p 8082:8082"
  end

  config.vm.provision :serverspec do |spec|
      spec.pattern = 'test/*_spec.rb'
  end
end

