Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/boot2docker"

  config.vm.provider "virtualbox" do |vb|
      vb.customize [ "modifyvm", :id, "--memory", "512"]
      vb.customize [ "modifyvm", :id, "--cpus", "1"]
  end

  config.vm.network "forwarded_port", host: 8081, guest: 8081
  config.vm.network "forwarded_port", host: 8082, guest: 8082

  if Vagrant.has_plugin?("vagrant-proxyconf")
    puts "proxyconf..."
    if ENV["http_proxy"]
      puts "http_proxy: " + ENV["http_proxy"]
      config.proxy.http   = ENV["http_proxy"]
    end
    if ENV["https_proxy"]
      puts "https_proxy: " + ENV["https_proxy"]
      config.proxy.https   = ENV["https_proxy"]
    end
    if ENV["no_proxy"]
      puts "no_proxy: "     + ENV["no_proxy"]
      config.proxy.no_proxy = ENV["no_proxy"]
    end
  end

  config.vm.provision "docker" do |d|
    d.run "train_data_service",         image: "pfichtner/docker-katatrainreservation-tds", args: "-p 8081:8081"
    d.run "booking_reference_service",  image: "pfichtner/docker-katatrainreservation-brs", args: "-p 8082:8082"
  end

  config.vm.provision :serverspec do |spec|
      spec.pattern = 'test/*_spec.rb'
  end
end

